### ISSUE TITLE
Escaped slashes are not processed properly.

### ISSUE THREAD

**Issue by pozix604** [jorge-leon/ton#1]
Escaped slashes are not decoded properly. For example:

    { "a": "09\/29\/2017" }

The value should be decoded as 09/29/2017.

Tcllib's json package does this properly.

**Comment by jorge-leon** [comment]
You are right.

The TON representation of this input is `o a [s {09\/29\/2017}]`

The "s" function is responsible for decoding JSON strings.  As stated in the README.md file in the section "Caveats", only backslash escaped quotes are taken care of by the three provided TON decoders.  A simple `format %s `_string_ should be sufficient for most purposes. You have (at least) the following options:
- Use **ton** as is and `format %s` on any string value you get.
- Use **ton** as is and write a decoder which does the `format %s`.
- Modify the (very short) source to make the decoder(s) do the `format %s` at once.
- Overwrite the decoder

Will provide an example ASAP

**Comment by pozix604** [comment]
Thanks. I've already done that. Just noting this here because the page claims that `ton::a2dict`produces a dictionary in the same format as the Tcllib parser, and it does't.

**Comment by jorge-leon** [comment]
> Thanks. I've already done that. Just noting this here because the page claims that `ton::a2dict`produces a dictionary in the same format as the Tcllib parser, and it does't.

Thanks for pointing this out. What I meant to say, was that the dict _structure_ is the same format.

Anyways - I will add a ton::tcllibjson decoder and fix it both ways.

Did you use `format` or `subst` in your code? `format` won't work, as it doesn't do backslash substitutions.

**Comment by jorge-leon** [comment]
I made a new version: 0.5 with a new decoder - json2dict. It is available from the original darcs repository http://at.magma-soft.at/darcs/ton via http.  I will update the github repository as soon as I find the right darcs2git  script which I have lost times ago.
